# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1200, 900)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.importStarBtn = QtWidgets.QPushButton(self.centralwidget)
        self.importStarBtn.setGeometry(QtCore.QRect(80, 30, 131, 51))
        self.importStarBtn.setObjectName("importStarBtn")
        self.importCsBtn = QtWidgets.QPushButton(self.centralwidget)
        self.importCsBtn.setGeometry(QtCore.QRect(80, 150, 131, 51))
        self.importCsBtn.setObjectName("importCsBtn")
        self.autoParserBtn = QtWidgets.QPushButton(self.centralwidget)
        self.autoParserBtn.setGeometry(QtCore.QRect(80, 270, 131, 51))
        self.autoParserBtn.setObjectName("autoParserBtn")
        self.custDbBtn = QtWidgets.QPushButton(self.centralwidget)
        self.custDbBtn.setGeometry(QtCore.QRect(80, 390, 131, 51))
        self.custDbBtn.setObjectName("custDbBtn")
        self.trainNNBtn = QtWidgets.QPushButton(self.centralwidget)
        self.trainNNBtn.setGeometry(QtCore.QRect(80, 510, 131, 51))
        self.trainNNBtn.setObjectName("trainNNBtn")
        self.pickBtn = QtWidgets.QPushButton(self.centralwidget)
        self.pickBtn.setGeometry(QtCore.QRect(80, 630, 131, 51))
        self.pickBtn.setObjectName("pickBtn")
        self.dbComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.dbComboBox.setGeometry(QtCore.QRect(400, 20, 441, 50))
        self.dbComboBox.setObjectName("dbComboBox")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(290, 0, 10, 900))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(850, 0, 10, 900))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.dbLabel = QtWidgets.QLabel(self.centralwidget)
        self.dbLabel.setGeometry(QtCore.QRect(320, 30, 61, 21))
        self.dbLabel.setObjectName("dbLabel")
        self.entryListView = QtWidgets.QListView(self.centralwidget)
        self.entryListView.setGeometry(QtCore.QRect(300, 100, 550, 740))
        self.entryListView.setObjectName("entryListView")
        self.helpBtn = QtWidgets.QPushButton(self.centralwidget)
        self.helpBtn.setGeometry(QtCore.QRect(80, 750, 131, 51))
        self.helpBtn.setObjectName("helpBtn")
        self.metaLabel = QtWidgets.QLabel(self.centralwidget)
        self.metaLabel.setGeometry(QtCore.QRect(1000, 30, 55, 16))
        self.metaLabel.setObjectName("metaLabel")
        self.voltageLabel = QtWidgets.QLabel(self.centralwidget)
        self.voltageLabel.setGeometry(QtCore.QRect(920, 90, 55, 16))
        self.voltageLabel.setObjectName("voltageLabel")
        self.csLabel = QtWidgets.QLabel(self.centralwidget)
        self.csLabel.setGeometry(QtCore.QRect(870, 140, 151, 16))
        self.csLabel.setObjectName("csLabel")
        self.psizeLabel = QtWidgets.QLabel(self.centralwidget)
        self.psizeLabel.setGeometry(QtCore.QRect(900, 190, 151, 16))
        self.psizeLabel.setObjectName("psizeLabel")
        self.dosageLabel = QtWidgets.QLabel(self.centralwidget)
        self.dosageLabel.setGeometry(QtCore.QRect(920, 240, 71, 16))
        self.dosageLabel.setObjectName("dosageLabel")
        self.voltageLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.voltageLineEdit.setGeometry(QtCore.QRect(1040, 90, 141, 22))
        self.voltageLineEdit.setObjectName("voltageLineEdit")
        self.csLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.csLineEdit.setGeometry(QtCore.QRect(1040, 140, 141, 22))
        self.csLineEdit.setObjectName("csLineEdit")
        self.psizeLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.psizeLineEdit.setGeometry(QtCore.QRect(1040, 190, 141, 22))
        self.psizeLineEdit.setObjectName("psizeLineEdit")
        self.doseLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.doseLineEdit.setGeometry(QtCore.QRect(1040, 240, 141, 22))
        self.doseLineEdit.setObjectName("doseLineEdit")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(850, 290, 351, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.infoLabel = QtWidgets.QLabel(self.centralwidget)
        self.infoLabel.setGeometry(QtCore.QRect(1010, 320, 55, 16))
        self.infoLabel.setObjectName("infoLabel")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(900, 360, 91, 16))
        self.label.setObjectName("label")
        self.numParticlesLabel = QtWidgets.QLabel(self.centralwidget)
        self.numParticlesLabel.setGeometry(QtCore.QRect(1090, 360, 55, 16))
        self.numParticlesLabel.setObjectName("numParticlesLabel")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(890, 410, 111, 16))
        self.label_2.setObjectName("label_2")
        self.numMicsLabel = QtWidgets.QLabel(self.centralwidget)
        self.numMicsLabel.setGeometry(QtCore.QRect(1090, 410, 55, 16))
        self.numMicsLabel.setObjectName("numMicsLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.importStarBtn.setText(_translate("MainWindow", "Import STAR file"))
        self.importCsBtn.setText(_translate("MainWindow", "Import CS file"))
        self.autoParserBtn.setText(_translate("MainWindow", "Auto Parser"))
        self.custDbBtn.setText(_translate("MainWindow", "Custom Databases"))
        self.trainNNBtn.setText(_translate("MainWindow", "Train NN"))
        self.pickBtn.setText(_translate("MainWindow", "Pick Particles"))
        self.dbLabel.setText(_translate("MainWindow", "Database"))
        self.helpBtn.setText(_translate("MainWindow", "Help"))
        self.metaLabel.setText(_translate("MainWindow", "Metadata"))
        self.voltageLabel.setText(_translate("MainWindow", "Voltage"))
        self.csLabel.setText(_translate("MainWindow", "Spherical Aberration (CS)"))
        self.psizeLabel.setText(_translate("MainWindow", "Pixel Size (A)"))
        self.dosageLabel.setText(_translate("MainWindow", "E- Dose"))
        self.infoLabel.setText(_translate("MainWindow", "Info"))
        self.label.setText(_translate("MainWindow", "No. of Particles"))
        self.numParticlesLabel.setText(_translate("MainWindow", "0"))
        self.label_2.setText(_translate("MainWindow", "No. of Micrographs"))
        self.numMicsLabel.setText(_translate("MainWindow", "0"))

